apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: $NAME_SPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: micro-test
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
