apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-server
  namespace: $NAME_SPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-server
  template:
    metadata:
      labels:
        app: sample-server
    spec:
      containers:
      - name: sample-server
        image: sample-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

