apiVersion: v1
kind: Service
metadata:
  name: sample-server
  namespace: $NAME_SPACE
spec:
  selector:
    app: sample-server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort

