apiVersion: v1
kind: Service
metadata:
  name: micro-test-mysql
  namespace: $NAME_SPACE
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: NodePort
